name: 'Setup Build Environment'
description: 'Setup Python, Rust, and build tools with caching'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  install-cargo-tools:
    description: 'Whether to install cargo tools'
    required: false
    default: 'true'
  install-python-deps:
    description: 'Whether to install Python build dependencies'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        rustflags: ""

    - name: Add Rust Targets
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          rustup target add wasm32-unknown-unknown x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu
        elif [ "${{ runner.os }}" == "macOS" ]; then
          rustup target add wasm32-unknown-unknown x86_64-apple-darwin aarch64-apple-darwin
        fi

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install Zig toolchain
      uses: mlugg/setup-zig@v2

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/zig
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install cargo tools
      if: inputs.install-cargo-tools == 'true'
      shell: bash
      run: |
        test -e ~/.cargo/bin/cargo-zigbuild || cargo install cargo-zigbuild
        test -e ~/.cargo/bin/rnr || cargo install rnr
        test -e ~/.cargo/bin/cargo-nextest || cargo install cargo-nextest
        test -e ~/.cargo/bin/cargo-binstall || cargo install cargo-binstall
        test -e ~/.cargo/bin/dx || cargo binstall dioxus-cli@0.7.0 -y
        test -e ~/.cargo/bin/trunk || cargo install trunk --locked

    - name: Install Python Build Dependencies
      if: inputs.install-python-deps == 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install build wheel toml maturin
